services:
  - type: web
    name: busco-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: NEWS_IMAGE_DISK
        value: cloudinary
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: MAIL_MAILER
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
